name: Generate Snake Animation

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: Syaptiyan
          outputs: |
            dist/github-snake-dark.svg?color_snake=green&color_dots=#bfd641,#8cc63f,#62a630,#4e8c2a,#3b6d22,#2a4e18
            dist/github-snake.svg

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
